name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter test

      - run: flutter analyze

      - run: flutter build apk
      - run: flutter build appbundle

      # Add additional steps like deploying to stores or generating documentation here

      # Upload artifacts for further analysis (optional)
      - upload: flutter_build/outputs/

